/**
 * Generated by `ztron codegen`. Do not edit by hand.
 * Run `ztron codegen` after adding/changing commands.
 */
import { invoke as rawInvoke } from "@zturnlibs/ztron-api";
import type { InvokeOptions } from "@zturnlibs/ztron-api";

export type KnownCommands = {
    "showcase:greet": { args: { name: string }; result: string }
    "showcase:add": { args: { a: number; b: number }; result: number }
    "showcase:echo": { args: { msg?: string }; result: string }
};

/** Type-safe invoke: cmd must be a known command, args/result inferred from its declaration. */
export function invoke<C extends keyof KnownCommands>(
  cmd: C,
  args: KnownCommands[C]["args"],
  options?: InvokeOptions,
): Promise<KnownCommands[C]["result"]>;

export async function invoke(
  cmd: string,
  args?: unknown,
  options?: InvokeOptions,
): Promise<unknown> {
  if (cmd === "showcase:greet") return rawInvoke(cmd, args as never, options);
  if (cmd === "showcase:add") return rawInvoke(cmd, args as never, options);
  if (cmd === "showcase:echo") return rawInvoke(cmd, args as never, options);
  return rawInvoke(cmd, (args ?? {}) as never, options);
}
export default invoke;
