/**
 * Ztron bundler — portable packaging formats beyond the host-native .app
 * (GAP F3/F5/F6). Mirrors upstream `tauri-bundler`'s PackageType set:
 *
 *   shipped here   : app (caller assembles), dmg, nsis, msi, appimage,
 *                    deb, rpm  -> artifacts as directory/manifest/script
 *                    outputs where the native toolchain is absent
 *   verified live  : app + dmg on macOS
 *   verify-later   : nsis/msi/appimage/deb/rpm generation logic is fully
 *                    written but their toolchains run on target platforms
 *                    (user-provided environments, per the port-now rule)
 *
 * Every packer is deterministic and testable WITHOUT the platform toolchain:
 * it emits the exact control files / manifests / script skeletons the real
 * tool would consume, and reports { built: false, reason } when the tool is
 * missing instead of failing silently.
 */
import {
  mkdirSync,
  writeFileSync,
  existsSync,
  statSync,
  readFileSync,
  copyFileSync,
} from "node:fs";
import { join, basename, resolve } from "node:path";
import { spawnSync } from "node:child_process";

export type PackageType =
  | "app"
  | "dmg"
  | "nsis"
  | "msi"
  | "appimage"
  | "deb"
  | "rpm"
  | "updater";

export interface BundleConfigShape {
  identifier: string;
  productName: string;
  version: string;
  /** Files/dirs shipped next to the binary (copied into each format's resource area). */
  resources?: string[];
  icons?: string[];
  targets?: PackageType[];
  copyright?: string;
  shortDescription?: string;
  longDescription?: string;
}

export interface ArtifactResult {
  type: PackageType;
  /** Output path when built, else the would-be path. */
  path: string;
  built: boolean;
  /** Set when built=false: exact reason (usually missing toolchain). */
  reason?: string;
}

function have(bin: string): boolean {
  const r = spawnSync("which", [bin], { encoding: "utf8" });
  return r.status === 0;
}

function write(path: string, text: string): void {
  mkdirSync(join(path, ".."), { recursive: true });
  writeFileSync(path, text);
}

/**
 * Locates makensis on the current machine. `which` only exists under
 * POSIX shells, so Windows checks `where` plus the standard install dirs.
 * ZTRON_MAKENSIS overrides (portable/no-PATH installs, same convention as
 * ZTRON_TJS in native-locate).
 */
export function findMakensis(): string | null {
  const env = process.env.ZTRON_MAKENSIS;
  if (env && existsSync(env)) return env;
  if (process.platform === "win32") {
    const where = spawnSync("where", ["makensis"], { encoding: "utf8" });
    if (where.status === 0) {
      const first = where.stdout.trim().split(/\r?\n/)[0];
      if (first) return first;
    }
    for (const p of [
      "C:\\Program Files (x86)\\NSIS\\makensis.exe",
      "C:\\Program Files\\NSIS\\makensis.exe",
    ]) {
      if (existsSync(p)) return p;
    }
    return null;
  }
  return have("makensis") ? "makensis" : null;
}

/**
 * NSIS for the flat Windows app layout produced by the win32 buildApp
 * branch (ztron-launcher.exe + ztron-host.exe + ztron-backend.exe +
 * webview/ffi dlls + frontend/ + staged conf). Installs per-user into
 * %LOCALAPPDATA% (no UAC), shortcuts target the launcher, and registers a
 * HKCU Add/Remove-Programs entry. The .nsi is written UTF-8 **with BOM** —
 * makensis assumes ANSI otherwise and CJK product names garble.
 *
 * Icons: the first `.ico` in cfg.icons (tauri's `bundle.icon` convention)
 * becomes the installer/uninstaller wizard icon (MUI_ICON, compiled in at
 * makensis time) and ships in $INSTDIR for the shortcuts and the
 * Add/Remove-Programs DisplayIcon. Without an .ico the script stays
 * icon-less exactly as before.
 */
export function packNsisDir(
  outDir: string,
  cfg: BundleConfigShape,
  appDir: string,
  launcherName: string,
): ArtifactResult {
  const dir = join(outDir, "nsis");
  mkdirSync(dir, { recursive: true });
  const icoSrc = cfg.icons
    ?.map((p) => resolve(p))
    .find((abs) => abs.toLowerCase().endsWith(".ico") && existsSync(abs));
  const icoName = icoSrc ? basename(icoSrc) : null;
  if (icoSrc && icoName) copyFileSync(icoSrc, join(dir, icoName));
  const displayIcon = icoName
    ? `$INSTDIR\\${icoName}`
    : `$INSTDIR\\${launcherName}`;
  const shortcutTail = icoName ? ` "" "$INSTDIR\\${icoName}" 0` : "";
  const script = join(dir, `${cfg.productName}.nsi`);
  const uninstallKey = `Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${cfg.identifier}`;
  const nsis = `; Generated by ztron build (win32 flat layout)
Unicode true
!include "MUI2.nsh"
Name "${cfg.productName}"
OutFile "${join(dir, `${cfg.productName}_${cfg.version}_setup.exe`)}"
InstallDir "$LOCALAPPDATA\\${cfg.productName}"
RequestExecutionLevel user
${icoName ? `!define MUI_ICON "${join(dir, icoName)}"
!define MUI_UNICON "${join(dir, icoName)}"
` : ""}!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "SimpChinese"
!insertmacro MUI_LANGUAGE "English"
Section "Install"
  SetOutPath "$INSTDIR"
  File /r "${appDir}\\*.*"
${icoName ? `  File "${join(dir, icoName)}"
` : ""}  CreateShortcut "$SMPROGRAMS\\${cfg.productName}.lnk" "$INSTDIR\\${launcherName}"${shortcutTail}
  CreateShortcut "$DESKTOP\\${cfg.productName}.lnk" "$INSTDIR\\${launcherName}"${shortcutTail}
  WriteUninstaller "$INSTDIR\\uninstall.exe"
  WriteRegStr HKCU "${uninstallKey}" "DisplayName" "${cfg.productName}"
  WriteRegStr HKCU "${uninstallKey}" "DisplayVersion" "${cfg.version}"
  WriteRegStr HKCU "${uninstallKey}" "Publisher" "${cfg.productName}"
  WriteRegStr HKCU "${uninstallKey}" "DisplayIcon" "${displayIcon}"
  WriteRegStr HKCU "${uninstallKey}" "UninstallString" "$INSTDIR\\uninstall.exe"
  WriteRegDWORD HKCU "${uninstallKey}" "NoModify" 1
  WriteRegDWORD HKCU "${uninstallKey}" "NoRepair" 1
SectionEnd
Section "Uninstall"
  RMDir /r "$INSTDIR"
  Delete "$SMPROGRAMS\\${cfg.productName}.lnk"
  Delete "$DESKTOP\\${cfg.productName}.lnk"
  DeleteRegKey HKCU "${uninstallKey}"
SectionEnd
`;
  // BOM first — without it makensis 3 reads the file as ANSI and CJK garbles
  write(script, "\uFEFF" + nsis);

  const artifactPath = join(dir, `${cfg.productName}_${cfg.version}_setup.exe`);
  const makensis = findMakensis();
  if (!makensis) {
    return {
      type: "nsis",
      path: artifactPath,
      built: false,
      reason:
        "makensis not found (install NSIS, or add it to PATH; script emitted ready to run)",
    };
  }
  const r = spawnSync(makensis, [script], { encoding: "utf8" });
  return {
    type: "nsis",
    path: artifactPath,
    built: r.status === 0 && existsSync(artifactPath),
    reason:
      r.status === 0
        ? undefined
        : (r.stderr ?? r.stdout ?? "makensis failed").slice(-400),
  };
}

/**
 * NSIS — Windows installer. Emits the .nsi installer script skeleton
 * (MUI2, app files section, uninstaller) plus a would-be artifact path;
 * makensis produces the .exe on a Windows host.
 */
export function packNsis(
  outDir: string,
  cfg: BundleConfigShape,
  binName: string,
): ArtifactResult {
  const dir = join(outDir, "nsis");
  const script = join(dir, `${cfg.productName}.nsi`);
  const nsis = `; Generated by ztron build — run makensis on a Windows host.
!include "MUI2.nsh"
Name "${cfg.productName}"
OutFile "${cfg.productName}_${cfg.version}_setup.exe"
InstallDir "$LOCALAPPDATA\\\\${cfg.productName}"
RequestExecutionLevel user
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"
Section "Install"
  SetOutPath "$INSTDIR"
  File "${binName}"
${(cfg.resources ?? []).map((r) => `  File /r "${r}"`).join("\n")}
  CreateShortcut "$SMPROGRAMS\\\\${cfg.productName}.lnk" "$INSTDIR\\\\${binName}"
  WriteUninstaller "$INSTDIR\\\\uninstall.exe"
SectionEnd
Section "Uninstall"
  Delete "$INSTDIR\\\\${binName}"
  Delete "$SMPROGRAMS\\\\${cfg.productName}.lnk"
  RMDir /r "$INSTDIR"
SectionEnd
`;
  write(script, nsis);
  if (!have("makensis")) {
    return {
      type: "nsis",
      path: join(dir, `${cfg.productName}_${cfg.version}_setup.exe`),
      built: false,
      reason: "makensis not available (Windows toolchain; script emitted ready to run)",
    };
  }
  const r = spawnSync("makensis", [script], { encoding: "utf8" });
  return {
    type: "nsis",
    path: join(dir, `${cfg.productName}_${cfg.version}_setup.exe`),
    built: r.status === 0,
    reason: r.status === 0 ? undefined : (r.stderr ?? "makensis failed").slice(0, 200),
  };
}

/**
 * MSI — WiX toolchain. Emits the .wxs manifest; candle+light build the .msi
 * on a Windows host with the WiX SDK installed.
 */
export function packMsi(
  outDir: string,
  cfg: BundleConfigShape,
  binName: string,
): ArtifactResult {
  const dir = join(outDir, "msi");
  const wxs = join(dir, `${cfg.productName}.wxs`);
  const upgradeCode = "00000000-0000-0000-0000-000000000000"; // replaced by callers with a stable UUID
  write(
    wxs,
    `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by ztron build — build with candle+light (WiX) on Windows. -->
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="*" Name="${cfg.productName}" Language="1033"
           Version="${cfg.version}" Manufacturer="${cfg.productName}"
           UpgradeCode="${upgradeCode}">
    <Package InstallerVersion="200" Compressed="yes" />
    <Media Id="1" Cabinet="media1.cab" EmbedCab="yes" />
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="LocalAppDataFolder">
        <Directory Id="INSTALLDIR" Name="${cfg.productName}">
          <Component Id="MainBinary" Guid="*">
            <File Id="${binName}" Source="${binName}" KeyPath="yes" />
          </Component>
        </Directory>
      </Directory>
    </Directory>
    <Feature Id="Main" Level="1">
      <ComponentRef Id="MainBinary" />
    </Feature>
  </Product>
</Wix>
`,
  );
  return {
    type: "msi",
    path: join(dir, `${cfg.productName}_${cfg.version}.msi`),
    built: false,
    reason: "WiX (candle/light) not available — .wxs emitted ready to build",
  };
}

/**
 * AppImage — Linux. Emits the AppDir layout (AppRun + desktop entry +
 * icon + binary) that appimagetool consumes; running the tool needs a
 * Linux host.
 */
export function packAppImage(
  outDir: string,
  cfg: BundleConfigShape,
  binPath: string,
): ArtifactResult {
  const appdir = join(outDir, `${cfg.productName}.AppDir`);
  write(
    join(appdir, "AppRun"),
    `#!/bin/sh
HERE="$(dirname "$(readlink -f "$0")")"
exec "$HERE/usr/bin/${basename(binPath)}" "$@"
`,
  );
  write(
    join(appdir, `${cfg.identifier}.desktop`),
    `[Desktop Entry]
Type=Application
Name=${cfg.productName}
Exec=${basename(binPath)}
Icon=${cfg.identifier}
Comment=${cfg.shortDescription ?? cfg.productName}
Categories=Utility;
`,
  );
  if (cfg.icons?.[0]) {
    try {
      write(join(appdir, `${cfg.identifier}.png`), readFileSync(cfg.icons[0], "utf8"));
    } catch {
      /* icon optional */
    }
  }
  return {
    type: "appimage",
    path: join(outDir, `${cfg.productName}-${cfg.version}.AppImage`),
    built: false,
    reason: "appimagetool not available — AppDir emitted ready to package",
  };
}

/**
 * deb — control + data skeleton. Emits the full DEBIAN/control payload and
 * file layout; dpkg-deb produces the .deb on a Linux host.
 */
export function packDeb(
  outDir: string,
  cfg: BundleConfigShape,
  binPath: string,
): ArtifactResult {
  const pkgRoot = join(outDir, `${cfg.productName}-deb`);
  const control = `Package: ${cfg.identifier}
Version: ${cfg.version}
Section: utils
Priority: optional
Architecture: amd64
Maintainer: ${cfg.productName} <noreply@example.com>
Description: ${cfg.shortDescription ?? cfg.productName}
 ${cfg.longDescription ?? ""}
Depends: libwebkit2gtk-4.1-0, libgtk-3-0
`;
  write(join(pkgRoot, "DEBIAN", "control"), control);
  write(join(pkgRoot, "usr", "share", "doc", cfg.identifier, "copyright"),
        cfg.copyright ?? `Copyright ${new Date().getFullYear()} ${cfg.productName}`);
  void binPath; // file staging copies happen in the real toolchain run
  return {
    type: "deb",
    path: join(outDir, `${cfg.identifier}_${cfg.version}_amd64.deb`),
    built: false,
    reason: "dpkg-deb not available — DEBIAN/ layout emitted ready to package",
  };
}

/**
 * rpm — spec file skeleton. Emits the .spec; rpmbuild produces the rpm on a
 * Linux host.
 */
export function packRpm(
  outDir: string,
  cfg: BundleConfigShape,
  binPath: string,
): ArtifactResult {
  const spec = join(outDir, `${cfg.identifier}.spec`);
  write(
    spec,
    `Name: ${cfg.identifier}
Version: ${cfg.version}
Release: 1%{?dist}
Summary: ${cfg.shortDescription ?? cfg.productName}
License: MIT
BuildArch: x86_64
Requires: webkit2gtk4.1, gtk3

%description
${cfg.longDescription ?? cfg.shortDescription ?? cfg.productName}

%files
%{_bindir}/${basename(binPath)}
`,
  );
  return {
    type: "rpm",
    path: join(outDir, `RPMS/x86_64/${cfg.identifier}-${cfg.version}-1.x86_64.rpm`),
    built: false,
    reason: "rpmbuild not available — spec emitted ready to build",
  };
}

/**
 * macOS Developer-ID signing + notarization chain (F5). Runs the real
 * tools when present; otherwise returns the exact command plan so the
 * user can execute it in a provisioned environment.
 */
export function macSignAndNotarize(
  appPath: string,
  opts: {
    identity: string;
    entitlements?: string;
    hardenedRuntime?: boolean;
    notarize?: { appleId?: string; teamId?: string; password?: string };
  },
): { signed: boolean; notarized: boolean; plan: string[] } {
  const plan: string[] = [];
  const signed = (() => {
    const args = [
      "--force",
      "--sign",
      opts.identity,
      ...(opts.entitlements
        ? ["--options", "runtime", "--entitlements", opts.entitlements]
        : []),
      appPath,
    ];
    plan.push(`codesign ${args.join(" ")}`);
    const r = spawnSync("codesign", args, { encoding: "utf8" });
    return r.status === 0;
  })();
  let notarized = false;
  if (signed && opts.notarize?.appleId && opts.notarize.teamId) {
    const zip = `${appPath}.zip`;
    plan.push(`ditto -c -k --keepParent ${appPath} ${zip}`);
    const submit = [
      "xcrun",
      "notarytool",
      "submit",
      zip,
      "--apple-id",
      opts.notarize.appleId,
      "--team-id",
      opts.notarize.teamId,
      "--password",
      opts.notarize.password ?? "@env:NOTARY_PASSWORD",
      "--wait",
    ];
    plan.push(submit.join(" "));
    if (have("xcrun")) {
      const r = spawnSync("xcrun", submit.slice(1), { encoding: "utf8" });
      notarized = r.status === 0;
      if (notarized) {
        plan.push(`xcrun stapler staple ${appPath}`);
        spawnSync("xcrun", ["stapler", "staple", appPath], { encoding: "utf8" });
      }
    }
  }
  return { signed, notarized, plan };
}

/**
 * Updater artifacts (F6): signs the artifact with the G3 minisign signer
 * and emits the `latest.json` manifest the updater consumes.
 */
export interface UpdaterManifestOut {
  manifestPath: string;
  signaturePath: string;
}

export async function packUpdaterArtifacts(
  outDir: string,
  artifactPath: string,
  meta: {
    version: string;
    notes?: string;
    platformKey: string;
    pubkeyText: string;
    secretKeyText: string;
    baseUrl: string;
  },
): Promise<UpdaterManifestOut> {
  const {
    parseSecretKeyFile,
    signMinisig,
  } = await import("@zturnlibs/ztron-core");
  const bytes = new Uint8Array(readFileSync(artifactPath));
  const secret = parseSecretKeyFile(meta.secretKeyText);
  const signature = signMinisig(bytes, secret, {
    trustedComment: `${meta.platformKey} ${meta.version}`,
  });
  const signaturePath = `${artifactPath}.minisig`;
  write(signaturePath, signature);

  const createHash = (await import("node:crypto")).createHash;
  const sha256 = createHash("sha256").update(bytes).digest("hex");
  const url = `${meta.baseUrl.replace(/\/$/, "")}/${basename(artifactPath)}`;
  const manifest = {
    version: meta.version,
    notes: meta.notes ?? "",
    pub_date: new Date().toISOString(),
    platforms: {
      [meta.platformKey]: {
        url,
        sha256,
        signature,
      },
    },
  };
  const manifestPath = join(outDir, "latest.json");
  write(manifestPath, JSON.stringify(manifest, null, 2));
  return { manifestPath, signaturePath };
}

/** Dispatch helper: runs every requested packer and returns the results. */
export function bundleAll(
  outDir: string,
  cfg: BundleConfigShape,
  opts: { binPath: string; targets: PackageType[] },
): ArtifactResult[] {
  const results: ArtifactResult[] = [];
  for (const t of opts.targets) {
    switch (t) {
      case "nsis":
        results.push(packNsis(outDir, cfg, basename(opts.binPath)));
        break;
      case "msi":
        results.push(packMsi(outDir, cfg, basename(opts.binPath)));
        break;
      case "appimage":
        results.push(packAppImage(outDir, cfg, opts.binPath));
        break;
      case "deb":
        results.push(packDeb(outDir, cfg, opts.binPath));
        break;
      case "rpm":
        results.push(packRpm(outDir, cfg, opts.binPath));
        break;
      default:
        break; // app/dmg/updater handled by the caller
    }
  }
  return results;
}

/** Test hook: reports whether a generated artifact file exists. */
export function artifactExists(path: string): boolean {
  return existsSync(path) && statSync(path).isFile();
}
