/**
 * `ztron codegen` — scans command modules for `defineCommand` calls and
 * generates a type-safe `invoke` wrapper (the TS replacement for Tauri's
 * compile-time type generation).
 *
 * Input: any `*.ts` file under the app that calls `defineCommand(name, { args, result, handler })`.
 * Output: `<appRoot>/src/ztron-commands.ts` with per-command overloads.
 */
import ts from "typescript";
import {
  existsSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";

interface FoundCommand {
  name: string;
  argsType: string;
  resultType: string;
}

const BANNER = `/**
 * Generated by \`ztron codegen\`. Do not edit by hand.
 * Run \`ztron codegen\` after adding/changing commands.
 */
import { invoke as rawInvoke } from "@zturnlibs/ztron-api";
import type { InvokeOptions } from "@zturnlibs/ztron-api";

`;

/** Returns TS source files under `dir` (recursive). */
function tsFiles(dir: string): string[] {
  const out: string[] = [];
  const walk = (d: string) => {
    let entries: string[];
    try {
      entries = readdirSync(d);
    } catch {
      return;
    }
    for (const entry of entries) {
      const p = join(d, entry);
      let st: ReturnType<typeof statSync>;
      try {
        st = statSync(p);
      } catch {
        continue;
      }
      if (st.isDirectory()) {
        if (!entry.startsWith(".") && entry !== "node_modules") walk(p);
      } else if (entry.endsWith(".ts") && !entry.endsWith(".d.ts")) {
        out.push(p);
      }
    }
  };
  walk(dir);
  return out;
}

/** Extract commands from a single source file via the TS AST. */
function extractCommands(file: string, source: string): FoundCommand[] {
  const out: FoundCommand[] = [];
  const sf = ts.createSourceFile(
    file,
    source,
    ts.ScriptTarget.ESNext,
    true,
    ts.ScriptKind.TS,
  );

  const print = (node: ts.Node | undefined): string => {
    if (!node) return "unknown";
    // If the value is `{} as T` or `"" as T`, extract the type on the right.
    let text = node.getText(sf);
    if (ts.isAsExpression(node)) {
      text = node.type.getText(sf);
    } else if (ts.isTypeAssertionExpression(node)) {
      text = node.type.getText(sf);
    } else if (
      ts.isObjectLiteralExpression(node) ||
      ts.isStringLiteral(node) ||
      ts.isNumericLiteral(node) ||
      ts.isIdentifier(node)
    ) {
      // Object/string/number literals used as phantom types carry no runtime
      // value; keep them verbatim so the generated `.d.ts` compiles.
    }
    return text.replace(/\s+/g, " ").trim();
  };

  const visit = (node: ts.Node): void => {
    if (
      ts.isCallExpression(node) &&
      ts.isIdentifier(node.expression) &&
      node.expression.text === "defineCommand"
    ) {
      const nameArg = node.arguments[0];
      if (nameArg && ts.isStringLiteral(nameArg)) {
        const name = nameArg.text;
        let argsType = "unknown";
        let resultType = "unknown";
        const spec = node.arguments[1];
        if (spec && ts.isObjectLiteralExpression(spec)) {
          for (const prop of spec.properties) {
            if (ts.isPropertyAssignment(prop) && ts.isIdentifier(prop.name)) {
              const key = prop.name.text;
              if (key === "args") argsType = print(prop.initializer);
              if (key === "result") resultType = print(prop.initializer);
            }
          }
        }
        out.push({ name, argsType, resultType });
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(sf);
  return out;
}

/** Generates the typed invoke wrapper module. */
function render(commands: FoundCommand[]): string {
  const map = commands
    .map(
      (c) => `  "${c.name}": { args: ${c.argsType}; result: ${c.resultType} }`,
    )
    .join("\n  ");

  const bodies = commands
    .map(
      (c) =>
        `  if (cmd === "${c.name}") return rawInvoke(cmd, args as never, options);`,
    )
    .join("\n");

  return (
    BANNER +
    `export type KnownCommands = {\n  ${map}\n};\n\n` +
    `/** Type-safe invoke: ` +
    `cmd must be a known command, args/result inferred from its declaration. */\n` +
    `export function invoke<C extends keyof KnownCommands>(\n` +
    `  cmd: C,\n` +
    `  args: KnownCommands[C]["args"],\n` +
    `  options?: InvokeOptions,\n` +
    `): Promise<KnownCommands[C]["result"]>;\n\n` +
    `export async function invoke(\n` +
    `  cmd: string,\n` +
    `  args?: unknown,\n` +
    `  options?: InvokeOptions,\n` +
    `): Promise<unknown> {\n` +
    `${bodies}\n` +
    `  return rawInvoke(cmd, (args ?? {}) as never, options);\n` +
    `}\n` +
    `export default invoke;\n`
  );
}

/** Runs codegen for an app rooted at `cwd`. */
export async function codegen(cwd: string): Promise<void> {
  const entry = resolveEntrySafe(cwd);
  const srcDir = entry ? dirname(entry) : resolve(cwd, "src");
  const files = tsFiles(srcDir);

  const commands: FoundCommand[] = [];
  for (const file of files) {
    const source = readFileSync(file, "utf8");
    commands.push(...extractCommands(file, source));
  }

  // De-dupe by name (last wins)
  const unique = new Map<string, FoundCommand>();
  for (const c of commands) unique.set(c.name, c);

  const outputFile = join(srcDir, "ztron-commands.ts");
  writeFileSync(outputFile, render([...unique.values()]));

  const rel = relative(cwd, outputFile);
  console.log(`[ztron] codegen: ${unique.size} command(s) -> ${rel}`);
}

/** Resolves the app entry without importing the full CLI runtime. */
function resolveEntrySafe(cwd: string): string | null {
  try {
    const configPath = join(cwd, "ztron.conf.json");
    if (existsSync(configPath)) {
      const cfg = JSON.parse(readFileSync(configPath, "utf8")) as {
        entry?: string;
      };
      if (cfg.entry) return resolve(cwd, cfg.entry);
    }
  } catch {
    /* ignore */
  }
  const candidate = resolve(cwd, "src/main.ts");
  return existsSync(candidate) ? candidate : null;
}
