/**
 * Test manifests — the source of truth for "100% coverage".
 * `COMMANDS` lists every command the framework must register (built-in +
 * plugins). `API_EXPORTS` lists every value export the `@ztron/api` surface
 * must provide. Tests assert the running framework matches these exactly
 * (no missing, no extra).
 */

export const COMMANDS: readonly string[] = [
  // ---- core / event ----
  "plugin:event|listen",
  "plugin:event|unlisten",
  "plugin:event|emit",
  "plugin:event|emit_to",
  // ---- app / process ----
  "plugin:app|name",
  "plugin:app|version",
  "plugin:app|tauri_version",
  "plugin:app|get_config",
  "plugin:process|exit",
  "plugin:process|relaunch",
  // ---- window ----
  "plugin:webview|create",
  "plugin:window|close",
  "plugin:window|prevent_close",
  "plugin:window|destroy",
  "plugin:window|minimize",
  "plugin:window|unminimize",
  "plugin:window|toggle_maximize",
  "plugin:window|is_maximized",
  "plugin:window|is_minimized",
  "plugin:window|set_fullscreen",
  "plugin:window|is_fullscreen",
  "plugin:window|set_always_on_top",
  "plugin:window|center",
  "plugin:window|set_focus",
  "plugin:window|set_visible",
  "plugin:window|set_resizable",
  "plugin:window|set_opacity",
  "plugin:window|set_transparent",
  "plugin:window|set_decorations",
  "plugin:window|get_frame",
  "plugin:window|get_position",
  "plugin:window|get_state",
  "plugin:window|get_title",
  "plugin:window|get_theme",
  "plugin:window|get_scale_factor",
  "plugin:window|set_ignore_cursor_events",
  "plugin:window|set_cursor",
  "plugin:window|set_zoom",
  "plugin:window|set_shadow",
  "plugin:window|set_enabled",
  "plugin:window|set_position",
  "plugin:window|set_bounds",
  "plugin:window|start_dragging",
  "plugin:window|start_resize_dragging",
  "plugin:window|set_title",
  "plugin:window|set_size",
  // ---- tray ----
  "plugin:tray|create",
  "plugin:tray|set_title",
  "plugin:tray|set_tooltip",
  "plugin:tray|set_icon",
  "plugin:tray|destroy",
  // ---- menu ----
  "plugin:menu|create",
  "plugin:menu|set_as_app_menu",
  "plugin:menu|set_item_enabled",
  "plugin:menu|set_item_title",
  "plugin:menu|destroy",
  // ---- dialog ----
  "plugin:dialog|open",
  "plugin:dialog|save",
  "plugin:dialog|message",
  // ---- clipboard ----
  "plugin:clipboard|read_text",
  "plugin:clipboard|write_text",
  // ---- notification / shortcut / deep-link ----
  "plugin:notification|send",
  "plugin:global-shortcut|register",
  "plugin:global-shortcut|unregister",
  "plugin:deep-link|get_last_url",
  "plugin:image|from_bytes",
  "plugin:image|from_path",
  "plugin:image|destroy",
  // ---- fs ----
  "plugin:fs|read_text",
  "plugin:fs|write_text",
  "plugin:fs|read_dir",
  "plugin:fs|exists",
  "plugin:fs|remove",
  "plugin:fs|make_dir",
  "plugin:fs|copy",
  "plugin:fs|rename",
  "plugin:fs|stat",
  // ---- path ----
  "plugin:path|join",
  "plugin:path|resolve",
  "plugin:path|normalize",
  "plugin:path|is_absolute",
  "plugin:path|basename",
  "plugin:path|dirname",
  "plugin:path|extname",
  "plugin:path|sep",
  "plugin:path|home_dir",
  "plugin:path|temp_dir",
  "plugin:path|cwd",
  "plugin:path|app_data_dir",
  "plugin:path|app_config_dir",
  "plugin:path|app_cache_dir",
  "plugin:path|app_local_data_dir",
  "plugin:path|app_log_dir",
  "plugin:path|baseline_dir",
  "plugin:path|data_dir",
  "plugin:path|config_dir",
  "plugin:path|cache_dir",
  "plugin:path|font_dir",
  "plugin:path|desktop_dir",
  "plugin:path|document_dir",
  "plugin:path|download_dir",
  "plugin:path|picture_dir",
  "plugin:path|audio_dir",
  "plugin:path|video_dir",
  "plugin:path|public_dir",
  "plugin:path|template_dir",
  "plugin:path|runtime_dir",
  "plugin:path|executable_dir",
  "plugin:path|resource_dir",
  // ---- http ----
  "plugin:http|fetch",
  // ---- os ----
  "plugin:os|info",
  "plugin:os|platform",
  "plugin:os|arch",
  "plugin:os|hostname",
  "plugin:os|version",
  "plugin:os|homedir",
  "plugin:os|tmpdir",
  "plugin:os|sep",
  "plugin:os|locale",
  "plugin:os|type",
  "plugin:os|family",
  "plugin:os|eol",
  // ---- store ----
  "plugin:store|get",
  "plugin:store|set",
  "plugin:store|has",
  "plugin:store|delete",
  "plugin:store|clear",
  "plugin:store|keys",
  "plugin:store|values",
  "plugin:store|entries",
  "plugin:store|save_store",
  // ---- log ----
  "plugin:log|log",
  "plugin:log|trace",
  "plugin:log|debug",
  "plugin:log|info",
  "plugin:log|warn",
  "plugin:log|error",
  // ---- shell ----
  "plugin:shell|execute",
  "plugin:shell|execute_stream",
  "plugin:shell|open",
  // ---- sql ----
  "plugin:sql|load",
  "plugin:sql|execute",
  "plugin:sql|select",
  "plugin:sql|close",
  // ---- autostart ----
  "plugin:autostart|is_enabled",
  "plugin:autostart|enable",
  "plugin:autostart|disable",
  // ---- window-state ----
  "plugin:window-state|get",
  "plugin:window-state|save",
  "plugin:window-state|restore",
  // ---- single-instance ----
  "plugin:single-instance|is_primary",
  // ---- websocket ----
  "plugin:websocket|connect",
  "plugin:websocket|send",
  "plugin:websocket|disconnect",
  // ---- local-ip ----
  "plugin:local-ip|get",
  // ---- network ----
  "plugin:network|get_local_ipv4",
  "plugin:network|get_local_ipv6",
  "plugin:network|get_public_ip",
  // ---- upload ----
  "plugin:upload|upload",
  // ---- persisted-scope ----
  "plugin:persisted-scope|get",
  "plugin:persisted-scope|save",
  // ---- updater ----
  "plugin:updater|check",
  "plugin:updater|verify",
  "plugin:updater|download",
];

export const COMMAND_SET: ReadonlySet<string> = new Set(COMMANDS);

/** Value exports the `@ztron/api` package must provide. */
export const API_EXPORTS: readonly string[] = [
  "invoke",
  "internals",
  "transformCallback",
  "convertFileSrc",
  "isZtron",
  "Channel",
  "Resource",
  "listen",
  "once",
  "emit",
  "emitTo",
  "Window",
  "WebviewWindow",
  "getCurrentWebviewWindow",
  "setupDragRegion",
  "LogicalSize",
  "PhysicalSize",
  "LogicalPosition",
  "PhysicalPosition",
  "positioner",
  "getPosition",
  "setPosition",
  "getSize",
  "getFrame",
  "fs",
  "readText",
  "writeText",
  "readDir",
  "exists",
  "remove",
  "makeDir",
  "copyFile",
  "renameFile",
  "stat",
  "path",
  "join",
  "resolve",
  "normalize",
  "isAbsolute",
  "basename",
  "dirname",
  "extname",
  "homeDir",
  "tempDir",
  "cwd",
  "appDataDir",
  "appConfigDir",
  "appCacheDir",
  "appLocalDataDir",
  "appLogDir",
  "baselineDir",
  "dataDir",
  "configDir",
  "cacheDir",
  "fontDir",
  "desktopDir",
  "documentDir",
  "downloadDir",
  "pictureDir",
  "audioDir",
  "videoDir",
  "publicDir",
  "templateDir",
  "runtimeDir",
  "executableDir",
  "resourceDir",
  "http",
  "os",
  "osInfo",
  "platform",
  "arch",
  "homedir",
  "tmpdir",
  "locale",
  "type",
  "family",
  "eol",
  "store",
  "logger",
  "log",
  "trace",
  "debug",
  "logInfo",
  "warn",
  "logError",
  "shell",
  "open",
  "updater",
  "checkUpdate",
  "verifyUpdate",
  "downloadUpdate",
  "Database",
  "sql",
  "autostart",
  "isAutostartEnabled",
  "enableAutostart",
  "disableAutostart",
  "clipboard",
  "readClipboardText",
  "writeClipboardText",
  "tray",
  "createTray",
  "setTrayTitle",
  "setTrayTooltip",
  "setTrayIcon",
  "destroyTray",
  "onTrayClick",
  "Menu",
  "setAppMenu",
  "onMenuEvent",
  "dialog",
  "open",
  "save",
  "message",
  "notification",
  "sendNotification",
  "registerShortcut",
  "unregisterShortcut",
  "onShortcut",
  "globalShortcut",
  "singleInstance",
  "isPrimaryInstance",
  "onSecondInstance",
  "deepLink",
  "getCurrentUrl",
  "onDeepLink",
  "windowState",
  "getWindowState",
  "saveWindowState",
  "restoreWindowState",
  "websocket",
  "connect",
  "sendMessage",
  "disconnect",
  "localIp",
  "getLocalIpv4",
  "network",
  "getNetworkIpv4",
  "getLocalIpv6",
  "getPublicIp",
  "uploader",
  "upload",
  "persistedScope",
  "getPersistedScope",
  "savePersistedScope",
  "Image",
  "app",
  "getName",
  "getVersion",
  "getTauriVersion",
  "getConfig",
  "processApi",
  "exitApp",
  "relaunchApp",
];

export const API_EXPORT_SET: ReadonlySet<string> = new Set(API_EXPORTS);
